name: Build Godot Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Godot
      run: |
        wget https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_linux.x86_64.zip -O godot.zip
        unzip godot.zip -d godot
        mv godot/Godot_v4.2.2-stable_linux.x86_64 godot/godot
        chmod +x godot/godot

        wget https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_export_templates.tpz -O templates.zip
        mkdir -p ~/.local/share/godot/export_templates/4.2.2.stable
        unzip templates.zip -d ~/.local/share/godot/export_templates/4.2.2.stable

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Build Android APK
      run: |
        mkdir -p build/android
        ./godot/godot --headless --verbose --export-release "Android" build/android/game.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: build/android/game.apk
