name: Build Godot Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Godot
      uses: firebelley/setup-godot@v1
      with:
        version: 4.2.1
        export-templates: true

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Build Android APK
      run: |
        mkdir -p build/android
        godot --headless --export-release "Android" build/android/game.apk

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: build/android/game.apk
